/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedFlagsRouteImport } from './routes/red-flags'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as MapRouteImport } from './routes/map'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ClustersRouteImport } from './routes/clusters'
import { Route as ActionPlanRouteImport } from './routes/action-plan'
import { Route as IndexRouteImport } from './routes/index'

const RedFlagsRoute = RedFlagsRouteImport.update({
  id: '/red-flags',
  path: '/red-flags',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersRoute = ClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionPlanRoute = ActionPlanRouteImport.update({
  id: '/action-plan',
  path: '/action-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action-plan': typeof ActionPlanRoute
  '/clusters': typeof ClustersRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/matrix': typeof MatrixRoute
  '/red-flags': typeof RedFlagsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action-plan': typeof ActionPlanRoute
  '/clusters': typeof ClustersRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/matrix': typeof MatrixRoute
  '/red-flags': typeof RedFlagsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/action-plan': typeof ActionPlanRoute
  '/clusters': typeof ClustersRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/matrix': typeof MatrixRoute
  '/red-flags': typeof RedFlagsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action-plan'
    | '/clusters'
    | '/insights'
    | '/map'
    | '/matrix'
    | '/red-flags'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/action-plan'
    | '/clusters'
    | '/insights'
    | '/map'
    | '/matrix'
    | '/red-flags'
  id:
    | '__root__'
    | '/'
    | '/action-plan'
    | '/clusters'
    | '/insights'
    | '/map'
    | '/matrix'
    | '/red-flags'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionPlanRoute: typeof ActionPlanRoute
  ClustersRoute: typeof ClustersRoute
  InsightsRoute: typeof InsightsRoute
  MapRoute: typeof MapRoute
  MatrixRoute: typeof MatrixRoute
  RedFlagsRoute: typeof RedFlagsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/red-flags': {
      id: '/red-flags'
      path: '/red-flags'
      fullPath: '/red-flags'
      preLoaderRoute: typeof RedFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters': {
      id: '/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-plan': {
      id: '/action-plan'
      path: '/action-plan'
      fullPath: '/action-plan'
      preLoaderRoute: typeof ActionPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionPlanRoute: ActionPlanRoute,
  ClustersRoute: ClustersRoute,
  InsightsRoute: InsightsRoute,
  MapRoute: MapRoute,
  MatrixRoute: MatrixRoute,
  RedFlagsRoute: RedFlagsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
