/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StakeholdersRouteImport } from './routes/stakeholders'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RedFlagsRouteImport } from './routes/red-flags'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as MapRouteImport } from './routes/map'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HmisRouteImport } from './routes/hmis'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ClustersRouteImport } from './routes/clusters'
import { Route as BriefRouteImport } from './routes/brief'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActionPlanRouteImport } from './routes/action-plan'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefLinkedinRouteImport } from './routes/brief.linkedin'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const StakeholdersRoute = StakeholdersRouteImport.update({
  id: '/stakeholders',
  path: '/stakeholders',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RedFlagsRoute = RedFlagsRouteImport.update({
  id: '/red-flags',
  path: '/red-flags',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HmisRoute = HmisRouteImport.update({
  id: '/hmis',
  path: '/hmis',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersRoute = ClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefRoute = BriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionPlanRoute = ActionPlanRouteImport.update({
  id: '/action-plan',
  path: '/action-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefLinkedinRoute = BriefLinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => BriefRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action-plan': typeof ActionPlanRoute
  '/admin': typeof AdminRoute
  '/brief': typeof BriefRouteWithChildren
  '/clusters': typeof ClustersRoute
  '/copilot': typeof CopilotRoute
  '/events': typeof EventsRoute
  '/hmis': typeof HmisRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/matrix': typeof MatrixRoute
  '/publications': typeof PublicationsRoute
  '/red-flags': typeof RedFlagsRoute
  '/resources': typeof ResourcesRoute
  '/stakeholders': typeof StakeholdersRoute
  '/api/chat': typeof ApiChatRoute
  '/brief/linkedin': typeof BriefLinkedinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action-plan': typeof ActionPlanRoute
  '/admin': typeof AdminRoute
  '/brief': typeof BriefRouteWithChildren
  '/clusters': typeof ClustersRoute
  '/copilot': typeof CopilotRoute
  '/events': typeof EventsRoute
  '/hmis': typeof HmisRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/matrix': typeof MatrixRoute
  '/publications': typeof PublicationsRoute
  '/red-flags': typeof RedFlagsRoute
  '/resources': typeof ResourcesRoute
  '/stakeholders': typeof StakeholdersRoute
  '/api/chat': typeof ApiChatRoute
  '/brief/linkedin': typeof BriefLinkedinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/action-plan': typeof ActionPlanRoute
  '/admin': typeof AdminRoute
  '/brief': typeof BriefRouteWithChildren
  '/clusters': typeof ClustersRoute
  '/copilot': typeof CopilotRoute
  '/events': typeof EventsRoute
  '/hmis': typeof HmisRoute
  '/insights': typeof InsightsRoute
  '/map': typeof MapRoute
  '/matrix': typeof MatrixRoute
  '/publications': typeof PublicationsRoute
  '/red-flags': typeof RedFlagsRoute
  '/resources': typeof ResourcesRoute
  '/stakeholders': typeof StakeholdersRoute
  '/api/chat': typeof ApiChatRoute
  '/brief/linkedin': typeof BriefLinkedinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action-plan'
    | '/admin'
    | '/brief'
    | '/clusters'
    | '/copilot'
    | '/events'
    | '/hmis'
    | '/insights'
    | '/map'
    | '/matrix'
    | '/publications'
    | '/red-flags'
    | '/resources'
    | '/stakeholders'
    | '/api/chat'
    | '/brief/linkedin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/action-plan'
    | '/admin'
    | '/brief'
    | '/clusters'
    | '/copilot'
    | '/events'
    | '/hmis'
    | '/insights'
    | '/map'
    | '/matrix'
    | '/publications'
    | '/red-flags'
    | '/resources'
    | '/stakeholders'
    | '/api/chat'
    | '/brief/linkedin'
  id:
    | '__root__'
    | '/'
    | '/action-plan'
    | '/admin'
    | '/brief'
    | '/clusters'
    | '/copilot'
    | '/events'
    | '/hmis'
    | '/insights'
    | '/map'
    | '/matrix'
    | '/publications'
    | '/red-flags'
    | '/resources'
    | '/stakeholders'
    | '/api/chat'
    | '/brief/linkedin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionPlanRoute: typeof ActionPlanRoute
  AdminRoute: typeof AdminRoute
  BriefRoute: typeof BriefRouteWithChildren
  ClustersRoute: typeof ClustersRoute
  CopilotRoute: typeof CopilotRoute
  EventsRoute: typeof EventsRoute
  HmisRoute: typeof HmisRoute
  InsightsRoute: typeof InsightsRoute
  MapRoute: typeof MapRoute
  MatrixRoute: typeof MatrixRoute
  PublicationsRoute: typeof PublicationsRoute
  RedFlagsRoute: typeof RedFlagsRoute
  ResourcesRoute: typeof ResourcesRoute
  StakeholdersRoute: typeof StakeholdersRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stakeholders': {
      id: '/stakeholders'
      path: '/stakeholders'
      fullPath: '/stakeholders'
      preLoaderRoute: typeof StakeholdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/red-flags': {
      id: '/red-flags'
      path: '/red-flags'
      fullPath: '/red-flags'
      preLoaderRoute: typeof RedFlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hmis': {
      id: '/hmis'
      path: '/hmis'
      fullPath: '/hmis'
      preLoaderRoute: typeof HmisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters': {
      id: '/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief': {
      id: '/brief'
      path: '/brief'
      fullPath: '/brief'
      preLoaderRoute: typeof BriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-plan': {
      id: '/action-plan'
      path: '/action-plan'
      fullPath: '/action-plan'
      preLoaderRoute: typeof ActionPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/linkedin': {
      id: '/brief/linkedin'
      path: '/linkedin'
      fullPath: '/brief/linkedin'
      preLoaderRoute: typeof BriefLinkedinRouteImport
      parentRoute: typeof BriefRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BriefRouteChildren {
  BriefLinkedinRoute: typeof BriefLinkedinRoute
}

const BriefRouteChildren: BriefRouteChildren = {
  BriefLinkedinRoute: BriefLinkedinRoute,
}

const BriefRouteWithChildren = BriefRoute._addFileChildren(BriefRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionPlanRoute: ActionPlanRoute,
  AdminRoute: AdminRoute,
  BriefRoute: BriefRouteWithChildren,
  ClustersRoute: ClustersRoute,
  CopilotRoute: CopilotRoute,
  EventsRoute: EventsRoute,
  HmisRoute: HmisRoute,
  InsightsRoute: InsightsRoute,
  MapRoute: MapRoute,
  MatrixRoute: MatrixRoute,
  PublicationsRoute: PublicationsRoute,
  RedFlagsRoute: RedFlagsRoute,
  ResourcesRoute: ResourcesRoute,
  StakeholdersRoute: StakeholdersRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
